### ISSUE TITLE
Card For Bear Data

### ISSUE THREAD

**Issue by jamalbrowning** [jamalbrowning/bear-watcher#2]
#USER STORY 
As a dev I should create a function `bearCardBuilder = () => {}` which prints card to river-container.

#AC 
***When*** the dev creates the bear card
***they*** should create a function called with a bootstrap card 
```
bearCardBuilder = (bears) => {
let domString = ''

for (let i = 0; i < bears.length; i++) {
    const dino = bears[i];
domstring = `
<div class="card" style="width: 18rem;">
  <img src="..." class="${name}-card" alt="brown bear">
  <div class="card-body">
    <h5 class="card-title">${name}/h5>
  </div>
</div>`
};
};
printToDom (' ' , domString)
```
# Dev Notes
this should be in its on module data file.

**Comment by luketlancaster** [comment]
hey @jamalbrowning did you have a specific question about this?
